services:
  - type: web
    name: eco-track
    env: node
    buildCommand: bash render-build.sh
    startCommand: npm run start:web
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: PYTHON_VERSION
        value: 3.11
